repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.1.0
      hooks:
      -   id: debug-statements
      -   id: mixed-line-ending
      -   id: check-executables-have-shebangs
      -   id: check-added-large-files
      -   id: check-symlinks
      -   id: trailing-whitespace
          exclude: trace$


